# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('start_the', models.DateTimeField(auto_now_add=True, verbose_name='Date de debut')),
                ('end_the', models.DateTimeField(auto_now=True, verbose_name='Date de fin')),
                ('cover', models.ImageField(upload_to='articles')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=10)),
            ],
        ),
    ]
