# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name_plural': 'Me'},
        ),
    ]
