# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 14:04
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20180921_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20),
        ),
    ]
