# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20180921_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_the',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_the',
            field=models.DateField(verbose_name='Date de debut'),
        ),
    ]
