# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20180921_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='adress',
            field=models.TextField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='short_desc',
            field=models.TextField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
