# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20180922_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(default='plop', upload_to='articles'),
            preserve_default=False,
        ),
    ]
