# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_category_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, null=True, size=6),
        ),
    ]
