# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20180923_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='content',
        ),
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.ManyToManyField(blank=True, to='cv.Experience'),
        ),
    ]
