# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20180923_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.ManyToManyField(blank=True, to='cv.test'),
        ),
    ]
