# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20180923_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='content',
        ),
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
