# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_auto_20180923_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='content',
        ),
    ]
