# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_remove_experience_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.TextField(default='plop', max_length=3000),
            preserve_default=False,
        ),
    ]
