# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_experience_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='adress',
            new_name='address',
        ),
    ]
