# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_auto_20181004_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
