# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_auto_20181004_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='short_desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
