# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_auto_20181005_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='lvl',
            field=models.IntegerField(blank=True, choices=[(1, 'novice'), (2, 'advanced beginer'), (3, 'competent'), (4, 'professionnel'), (5, 'expert')], null=True),
        ),
    ]
