# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_auto_20181005_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='color',
        ),
    ]
