# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_auto_20181005_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='lvl',
            field=models.CharField(blank=True, choices=[('novice', 'novice'), ('advanced-beginer', 'advanced-beginer'), ('competent', 'competent'), ('professionnel', 'professionnel'), ('expert', 'expert')], max_length=100, null=True),
        ),
    ]
