# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0028_auto_20181007_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='lvl',
            field=models.CharField(blank=True, choices=[('NOVICE', 'novice'), ('ADVENCED', 'advanced-beginer'), ('COMPETENT', 'competent'), ('PRO', 'professionnel'), ('EXPERT', 'expert')], max_length=100, null=True),
        ),
    ]
