# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_auto_20181007_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='lvl',
            field=models.CharField(blank=True, choices=[(1, 'novice'), (2, 'advanced-beginer'), (3, 'competent'), (4, 'professionnel'), (5, 'expert')], max_length=100, null=True),
        ),
    ]
