# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0033_auto_20181011_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('lvl', models.CharField(blank=True, choices=[('novice', 'novice'), ('advanced-beginer', 'advanced-beginer'), ('competent', 'competent'), ('professionnel', 'professionnel'), ('expert', 'expert')], max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SpareTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Category')),
            ],
        ),
    ]
