# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0034_skill_sparetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='lvl',
        ),
        migrations.AlterField(
            model_name='skill',
            name='lvl',
            field=models.CharField(choices=[('novice', 'novice'), ('advanced-beginer', 'advanced-beginer'), ('competent', 'competent'), ('professionnel', 'professionnel'), ('expert', 'expert')], default='novice', max_length=100),
        ),
    ]
