# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0035_auto_20181011_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Abilities',
        ),
    ]
