# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0037_auto_20181011_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=3000, null=True)),
                ('start_the', models.DateField(blank=True, null=True, verbose_name='Date de debut')),
                ('end_the', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Category')),
            ],
        ),
    ]
