# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0038_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_the',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_the',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date de debut'),
        ),
    ]
